name: Android UI test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  instrumented-tests:
    name: Run tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [23, 32]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
        env:
          CI: true
          JAVA_TOOL_OPTIONS: -Xmx3g
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process